path_classifiers:
  library:
    - core/com.b2international.snowowl.api.rest/static/lib
    - core/com.b2international.snowowl.fhir.api/static/lib
    - snomed/com.b2international.snowowl.snomed.api.rest/static/lib
extraction:
  java:
    index:
      maven:
        version: 3.5.3