language: java
jdk:
  - openjdk11
sudo: required
install: true
before_script:
  - cp settings.xml $HOME/.m2/settings.xml
script: MAVEN_OPTS="-Xms2g -Xmx2g" mvn clean verify
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)