language: java
jdk:
  - oraclejdk8
sudo: required
install: true
script: MAVEN_OPTS="-Xms2g -Xmx2g" mvn clean verify --no-snapshot-updates
cache:
  directories:
  - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)