#
# Copyright 2011-2017 B2i Healthcare Pte Ltd, http://b2i.sg
#

# Default identity provider is PROP_FILE
# You can specify users in the configuration/users file in the form of <username>:<password>, where the password is BCrypt encrypted hash of the password
# The default user is snowowl with the password of snowowl
# NOTE: it is recommended to change the default username/password in production environments
#identity:
#  type: PROP_FILE

repository:
  port: 2036

# Request execution metrics (response-time, detailed information about transactions, etc.)
metrics:
  enabled: true

# reviewManager:
  # Minutes to keep reviews in CURRENT state persisted in the index (default 15 minutes)
  # keepCurrentMins: 15
  # Minutes to keep reviews in others states persisted (default 5 minutes)
  # keepOtherMins: 5